### ISSUE TITLE
End might be too specific

### ISSUE THREAD

**Issue by Glideh** [andyexeter/bump_version#1]
Thank you for this really interesting piece of code, I think i'll use it.
I think that the last part should however be less specific.
You might want to split the grunt and git part which is more a matter of choice.
I guess if you use grunt, this whole bump job could even be easier to do with grunt.

But again, I'll most likely use your code because I need to bump versions in `.env` files read by my docker build/push

**Comment by andyexeter** [comment]
Thank you for the feedback. I have to say I agree with you, I looked at using this in another project recently which I am not using Grunt for and I wondered why I had made it so tightly coupled.

I will look into decoupling it when I have some free time. If you wanted to take a look at doing it yourself I'd happily accept a PR.

**Comment by Glideh** [comment]
I used it successfully by simply removing what is after this line
https://github.com/andyexeter/bump_version/blob/7b00477f4f089c71a92765d2b3fddcc03f81179e/bump_version.sh#L83

The rest could be run separately with another task.
I currently have these 3 tasks: `bump`, `build`, `deploy`

**Comment by andyexeter** [comment]
I'd prefer not to just remove the functionality though. I'm going to look at setting up a post `bump` hooks directory which can be used to selectively execute different scripts after the version has been bumped such as committing to git.

**Comment by Glideh** [comment]
That could be great indeed

**Comment by andyexeter** [comment]
I've added pre/post bump hooks and moved the Grunt, git, and npm stuff into post bump hooks (061aa0e)
